name: spoco
services:
  frontend:
    build: 
      context: ../frontend
      dockerfile: docker/Dockerfile
      args:
        SUBPATH: /
    volumes:
      - node_modules_data:/app/node_modules
    ports:
      - "5000:80"
    depends_on:
      - backend
    networks:
      - spoco_net
  backend:
    build: 
      context: ..
      dockerfile: backend/docker/Dockerfile
    volumes:
      - ../settings:/settings
      - ../Corpus:/Corpus:ro
    environment:
      - DOCKER=True
    networks:
      - spoco_net

volumes:
  node_modules_data:

networks:
  spoco_net:
    driver:
      bridge
