services:
  frontend:
    build: 
      context: ../frontend
      dockerfile: docker/Dockerfile
      target: development
    volumes:
      - /app/node_modules
      - ../settings:/app/src/settings
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: 
      context: ../backend
      dockerfile: docker/Dockerfile
      target: development
    volumes:
      - ../backend:/app:delegated
      - ../settings:/app/settings
      - ../Corpus:/Corpus
    ports:
      - "8000:8000"
    environment:
      - ENV=development
